### ISSUE TITLE
Audio stops playing and sometimes doesn't play

### ISSUE THREAD

**Issue by orjanv** [ACMILabs/static-museum-audio-guide#2]
I've forked this repo and setup as explained. It appear to work fine and I can change the audio files and content as desired. However, I experience that the audio player stops playing after a few seconds on some devices and browser, but not always. Also it can sometimes play through the file but then will not let me play it again. 

I have tried different devices and browsers and the audio files are 128kbps 44.1khz MP3.

Any idea why this is happening?

**Comment by orjanv** [comment]
I tried at first to have a local dev version and hosted it using jekyll serve --host=0.0.0.0 parameter to reach it from other devices. I then tried to deploy the _site content instead to a nginx server under an official domain name, which seem to work better and the audio plays consistently. 

Is there a preferred way to deploy the static files?

**Comment by andrewserong** [comment]
I no longer work at ACMI so can't really offer too much in way of support, but: after running `jekyll build` you can pop the static files on virtually any web host. Easy to get started ones include [Github Pages](https://pages.github.com/) and [Netlify](https://www.netlify.com/), and both of them also support building the Jekyll site for you, which simplifies things a bit. But serving via nginx is a fine alternative, too, or even an S3 bucket.

I'd avoid trying to use `jekyll serve` for connecting other devices, I believe it's only really intended for local development, so probably doesn't handle multiple simultaneous requests very well. If audio is dropping out, it's possibly one of the following causes:

* When you start playing the file, the browser will perform HTTP range requests to get the rest of the file.
  * Browsers can be pretty aggressive about caching media files, so if the filename hasn't changed but you've changed the audio file, then the browser might have cached the first part of an older version of the file, but do the range request grabbing a section of the new file from the server, leading to a corrupt file in memory. If you're iterating on the audio files, rename them as you go.
  * If you're not serving from a "real" web server (e.g. if you're using `jekyll serve` instead of nginx or a web host) then these subsequent HTTP range requests are likely to fail unexpectedly leading to dropouts.

If you find you're getting dropouts in real world situations, like over patchy WiFi, another approach can be to optimise your MP3 files, by making them mono 64kbps (roughly the same quality as a stereo 128kbps file, but a smaller file).

Finally, the included JS libraries in this repo are pretty out of date by now. If you're using this project in production, you might want to take a look at swapping these out for the latest CDN versions or bundling and minifying your own.

Hope that helps!

**Comment by orjanv** [comment]
Thanks for the thorough answer @andrewserong. I won't serve the static direcoty with jekyll serve, but perhaps a local webserver, so i think it will be fine. Also, thanks for the tips on what to avoid. 

Thanks,
Ørjan
